### ISSUE TITLE
M1: Generate set of data for testing and development

### ISSUE THREAD

**Issue by Unnil** [montevideo-tech/cmcd-validator#1]
**As a** developer
**I want to** have a set of data available for testing the library implementation
**So that** i can validate that the CMCD validator is actually working in regards with the CMCD standard

Basically data that contains CMCD data to be able to test the implementation

Acceptance criteria:
- Push to the a file  examples/cmcd-data-samples.txt containing sample data retrieved from some player.

Resources/Hints:
- HLS.js already has cmcd implemented, it can be turn on by config.
- Use browser network analysis to find the CMCD headers or queryparams ;)

**Comment by CamiloBorba09** [comment]
The player from the following link was used to obtein the query database https://reference.dashif.org/dash.js/latest/samples/advanced/cmcd.html.

To obtain the headers database, I used the following player https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html . This player also allows to obtein the CMCD report in queries.

**Comment by CamiloBorba09** [comment]
I put 20 examples on **cmcd-data-samples-header** and in **cmcd-data-samples-queries**.  @pollingerMaxi and @Unnil. Could you check if it is ok for you? Should we need to add more?

**Comment by mpollingerQualabs** [comment]
@CamiloBorba09 please create a PR and link this issue

**Comment by CamiloBorba09** [comment]
Since I could´t find any sample related to the json format I added the examples mentioned in the standard.
