### ISSUE TITLE
Design library architecture

### ISSUE THREAD

**Issue by mpollingerQualabs** [montevideo-tech/cmcd-validator#10]
Create a design (e.g.: components diagram) of how the internal architecture of the library will work.

Consider the inputs (exposed functions), the validations per input, common parsed input (maybe convert every input to a common format), generic validator function, etc.

**Acceptance criteria**:
- Design of the architecture is presented in a graphical format (diagram)
- All internal components are considered in the design
- Design should enable a developer to implement the code for the library

**Comment by mcamardon** [comment]
Today we discussed with Gabriel on a possible design for the library architecture. The idea would be something like the image below. 

![Image](https://user-images.githubusercontent.com/124176760/218185193-b7357b88-cc02-4c3d-a19a-94f9e54f59d8.png)


- Input:  as a first approach we thought the input could be one of the three format (query argument, header or json object). 
- Main: based on the input, it decides what to execute next (parser, validator, log)
- Parser: this module can be used to transform the format. For example from query to json object.
- Validator: this module validates the input based on CTA-5004. This could also check if there are any custom keys.
- Log: It could be useful to display input or any other relevant information.
- Output: output to e defined in ticket https://github.com/montevideo-tech/cmcd-validator/issues/6
- Conf: this is meant to configure the input if it comes with a custom key.

This is just a first sketch, please feel free to bring any suggestions, everything can be discussed.

**Comment by gdavila** [comment]
This is a duplicated issue from #16

@mcamardon Please close one of them. I'd prefer to continue working over the google document since it is better to edit/draft the architecture details at early  stages.

**Comment by CamiloBorba09** [comment]
@gdavila . We discussed with the team and the first idea that came up regarding the architecture of the library is the following.



![Image](https://user-images.githubusercontent.com/99991582/218832667-b5eeee84-1a32-406c-877b-25b724d7b8b9.png)

We can talk about this on Friday's retrospective. I'm going to close this ticket.
