### ISSUE TITLE
Create DASH fragmented mp4 asset

### ISSUE THREAD

**Issue by mpollingerQualabs** [montevideo-tech/cmcd-validator#111]
Using a sample video (less than 5minutes) create a DASH fragmented mp4 playlist (extension `.mpd`).

This DASH video needs to be uploaded to a CDN and be publicly available.
Asset needs to be available to be played using the CMCD validator.

AWS MediaConvert could be used to create this asset.

Acceptance criteria
* Asset is DASH fragmented mp4
* URL extension is `.mpd`
* Asset is publicly available
* Asset can be used in the CMCD validator
* Link to asset is added as a comment in this issue

**Comment by JoaquinBCh** [comment]
Dash asset: https://dxclj9vp3m44c.cloudfront.net/dash/Costa_Rica_144.mpd
hls asset: https://dxclj9vp3m44c.cloudfront.net/hls/Costa_Rica_144.m3u8

**Comment by JoaquinBCh** [comment]
`{
  "Queue": "<Queue>",
  "UserMetadata": {},
  "Role": "<IAM-Role>",
  "Settings": {
    "TimecodeConfig": {
      "Source": "ZEROBASED"
    },
    "OutputGroups": [
      {
        "Name": "DASH ISO",
        "Outputs": [
          {
            "ContainerSettings": {
              "Container": "MPD"
            },
            "VideoDescription": {
              "Width": 720,
              "Height": 480,
              "CodecSettings": {
                "Codec": "H_264",
                "H264Settings": {
                  "MaxBitrate": 50000,
                  "RateControlMode": "QVBR",
                  "SceneChangeDetect": "TRANSITION_DETECTION"
                }
              }
            },
            "NameModifier": "_output1"
          },
          {
            "ContainerSettings": {
              "Container": "MPD"
            },
            "AudioDescriptions": [
              {
                "CodecSettings": {
                  "Codec": "AAC",
                  "AacSettings": {
                    "Bitrate": 96000,
                    "CodingMode": "CODING_MODE_2_0",
                    "SampleRate": 48000
                  }
                }
              }
            ],
            "NameModifier": "_output2"
          },
          {
            "ContainerSettings": {
              "Container": "MPD"
            },
            "VideoDescription": {
              "Width": 640,
              "Height": 360,
              "CodecSettings": {
                "Codec": "H_264",
                "H264Settings": {
                  "MaxBitrate": 10000,
                  "RateControlMode": "QVBR",
                  "SceneChangeDetect": "TRANSITION_DETECTION"
                }
              }
            },
            "NameModifier": "_output3"
          }
        ],
        "OutputGroupSettings": {
          "Type": "DASH_ISO_GROUP_SETTINGS",
          "DashIsoGroupSettings": {
            "SegmentLength": 10,
            "Destination": "s3://cmcd-video-demo/dash/",
            "FragmentLength": 2,
            "MpdProfile": "ON_DEMAND_PROFILE"
          }
        }
      }
    ],
    "Inputs": [
      {
        "AudioSelectors": {
          "Audio Selector 1": {
            "DefaultSelection": "DEFAULT"
          }
        },
        "VideoSelector": {},
        "TimecodeSource": "ZEROBASED",
        "FileInput": "s3://<bucket-name>/Costa_Rica_144.mp4"
      }
    ]
  },
  "AccelerationSettings": {
    "Mode": "DISABLED"
  },
  "StatusUpdateInterval": "SECONDS_60",
  "Priority": 0
}`
