### ISSUE TITLE
M2: Design mockups for the UI

### ISSUE THREAD

**Issue by mpollingerQualabs** [montevideo-tech/cmcd-validator#13]
Design basic mockups so that it's easier for developers to code the UI.

Designs could be made by hand, figma, balsamiq, draw.io, or any other software that has the capability to create mockups. 
Preferably, if using a tool, use a collaborative tool and free.

**Acceptance criteria**:
- Mockups are publicly available

**Comment by JoaquinBCh** [comment]
https://www.figma.com/file/VzrBaW3hKUc9HfRjMoDlwR/muckup-App-Demo-CMCD-Validator
