### ISSUE TITLE
M2: Update github pages with latest demo app version.

### ISSUE THREAD

**Issue by JoaquinBCh** [montevideo-tech/cmcd-validator#166]
AC: 
- Update github page with latest demo app version.

**Comment by JoaquinBCh** [comment]
We could fix the pusblish commenting a line in gh-pages deploy, so we need to fix this later.

**Comment by CamiloBorba09** [comment]
Status: 
This ticket is blocked by:
- https://github.com/montevideo-tech/cmcd-validator/issues/142
- https://github.com/montevideo-tech/cmcd-validator/issues/192
