### ISSUE TITLE
M1.5: Key validation and error reporting validator configuration

### ISSUE THREAD

**Issue by arrivillagaTomas** [montevideo-tech/cmcd-validator#18]
As a developer incorporating CMCD to my player I want to be able to receive errors in a validation attempt tailored to my current needs. I want to be able to set a configuration so that the validator omits errors that are not useful for my implementation. I also want to be able to have certain control over which keys should the validator take into account when outputing a result.

The implementation for applying the validation restriction on the object should be straightforward. Given a conguration `config`, the configuration should be passed in to the validator's constructor such as `validator = new CMCDValidator(config)`. It should also be modifiable through a `.setConfig(config)` method.
If the validator is not configured, all keys should be validated and all errors should be made available.

**Acceptance criteria:**
	Define configuration object and its purpose

**Comment by arrivillagaTomas** [comment]
### Initial proposal:
The configuration object should have two fields, `"keys`" and `"level"`.
The `"keys"` field is to be an array of strings. Their value should correspond to the CMCD Standard key names that the user wants to validate.
The `"level"` field if to be a single string with values `"error"`, `"warn"` or `"info"`. 
Assigning a criticality rating to each type of failed validation attempt, the "level" will work as a filter of what type of message to show or not show. The levels are self encompassing given their criticality, so that if the user chooses a `"info"` level, the user will receive `"info`", `"warn"` and `"error"` types of messages. If they choose a `'warn'` level, only `'warn'` and `'error'` types of messages will be displayed. Definition of `'info'`, `'warn'` or `'error`' messages is out of the scope of this ticket.

Example configuration object: 
```
	const config = {
	    keys: ['sid', 'cid', 'br'],
	    level: 'warn'
	}
```
Given this configuration I expect to receive validation only on Session ID (sid), Content ID(cid) and Encoded Bitrate()br keys, regardless of the input I send. I also expect to receive messages up to the warn level.

**Comment by gdavila** [comment]
@arrivillagaTomas - please check the [high level definitions ](https://docs.google.com/document/d/1rBNKa5HcUAKghXtoOcVn9iw-Qae8L0K_Z8TAJnqpKyU/edit#heading=h.aiwl9qups724)on the issue #16. Some of them are related to this one but with a more general approach for doing configurations for the entire library.

**Comment by CamiloBorba09** [comment]
@arrivillagaTomas we created the ticket https://github.com/montevideo-tech/cmcd-validator/issues/85 to reduce the scope of this ticket but to work on this feature.
