### ISSUE TITLE
[BUG] the name of the exported library for browser should not have the '-' char in its name

### ISSUE THREAD

**Issue by nicolaslevy** [montevideo-tech/cmcd-validator#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we export the library for browsers, the global variable for the library is ''cmcd-validator-debug" (checkout https://cdn.jsdelivr.net/npm/@montevideo-tech/cmcd-validator@1.0.0/dist/cmcd-validator.umd.js)

The '-' character on the name of the library makes that we can not access to the variable using `window.cmcd-validator-debug`

### Expected Behavior

This should work in browsers:

`window.CMCDValidator`

To do that we should:
- Change the library name in rollup to 'CMCDValidator' (also removing the "debug" part of the name)
- Fix the README 

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/6704577/234410733-dbc17323-1b34-433c-860a-f396620bf417.png)

**Comment by CamiloBorba09** [comment]
Bug has been fixed.

Here is a screenshot where we show how you can call the library.


![Image](https://user-images.githubusercontent.com/99991582/234930976-4c71754d-afce-431c-a9c9-111d440cb926.png)
