### ISSUE TITLE
[Question] Add a example with Bitmovin Player CMCD integration

### ISSUE THREAD

**Issue by gdavila** [montevideo-tech/cmcd-validator#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

What should be the best approach to add an example of  the cmcd-validator  with Bitmovin Player to the [demo-apps](https://github.com/montevideo-tech/cmcd-validator/tree/develop/packages/cmcd-validator-demo-app)?

I have a [sample code](https://github.com/gdavila/cmcd-bitmovin/blob/main/js/script.js#L58)  already integrated with cmcd-validator based on [Bitmovin public CMCD example](https://github.com/bitmovin/demos/tree/develop/player/cmcd). However it seems that your demo-app follow a specific design I'm not fully familiar with.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by nicolaslevy** [comment]
Awesome!! Thank you @gdavila!  We will take a look at it and add it to the example app :D

**Comment by JoaquinBCh** [comment]
Hi @gdavila, I'm working adding bitmovin player to the example app, I assigned the branch I'm working to this ticket.
Dou you have time to help me with this? 
I'm having trouble with the ui of the player and I dont undestand how to include cmcd.
