### ISSUE TITLE
M1: Configure the library repo

### ISSUE THREAD

**Issue by Unnil** [montevideo-tech/cmcd-validator#2]
Objective: Setup everything we need to setup a NPM package.

**Acceptance criteria**:
- Use the name `cmcd-validator` as the name is not used in npm
- The library must have the same license as this repo
- Configure some linter

**Comment by CamiloBorba09** [comment]
I created the setup of the library. We have the following folders:

- src: in this folder we are going to add all the code that we need
- src/contollers: we are going to add all the logic related to our routes
- src/reoutes: the routes that we are going to have
- .env: where we define our global variables
- package.json: all the information about our project.

FYI:
- I added nomdemon as dev module to make the develop esasly.
