### ISSUE TITLE
M1: Implement parse function from Header to Json

### ISSUE THREAD

**Issue by CamiloBorba09** [montevideo-tech/cmcd-validator#21]
We need a function to parse from query to json. Here you have some examples.

1.

Input

CMCD-Session:sid="6e2fb550-c457-11e9-bb97-0800200c9a66"

Output

{"sid": "6e2fb550-c457-11e9-bb97-0800200c9a66"}

2.

Input

CMCD-Request:mtp=25400
CMCD-Object:br=3200,d=4004,ot=v,tb=6000
CMCD-Status:bs,rtp=15000
CMCD-Session:sid="6e2fb550-c457-11e9-bb97-0800200c9a66"

Output

{"br": 3200,"bs":true,"d": 4004,"mtp": 25400, "ot": "v", "rtp":15000,"sid":
"6e2fb550-c457-11e9-bb97-0800200c9a66","tb":6000}

3.

Input

CMCD-Status:bs,rtp=15000
CMCD-Session:sid="6e2fb550-c457-11e9-bb97-0800200c9a66"

Output:

{"bs":true,"rtp":15000,"sid": "6e2fb550-c457-11e9-bb97-0800200c9a66"}

**Acceptance criteria**:
1. Create a function to parse from Header to Json

**Comment by Rspillere** [comment]
I had a problem with the linked pull request, so I closed it and created a new one. [new PR](https://github.com/montevideo-tech/cmcd-validator/pull/46)
