### ISSUE TITLE
M1: Implement output of the library

### ISSUE THREAD

**Issue by CamiloBorba09** [montevideo-tech/cmcd-validator#23]
Based on the discussion in the ticket [[M1: Define output interface (response of the main functions) of the library](https://github.com/montevideo-tech/cmcd-validator/issues/6)](https://github.com/montevideo-tech/cmcd-validator/issues/6 ) we need to make a function that has the following inputs:

**Input:**
- error: with the following structure.
 ```
"errors": [
    {
      "type": <missing-header|parameter-value|parameter-encoding|missing-parameter|invalid-header|unknown-parameter|invalid-header-encoding|invalid-json|etc...>,
      "key": <string>
      "value": <any-type>
      "description": <string (description for humans)>
    }
```
- parsedData: < json >
- rawData: <string, json or object with 3 headers and the strings>

**Output:**
- json with the following format:

```
{
 "valid": <bool>,
 "errors": [
    {
      "type": <missing-header|parameter-value|parameter-encoding|missing-parameter|invalid-header|unknown-parameter|invalid-header-encoding|invalid-json|etc...>,
      "key": <string>
      "value": <any-type>
      "description": <string (description for humans)>
    },
    {...},
  ]
  "parsedData": <json>
  "rawData": <string, json or object with 3 headers and the strings>
}
```
**valid:** true when there are no errors; false otherwise.

**Comment by sebastianpiq** [comment]
The output should be with JSON.stringfy() or just the Object?

**Comment by CamiloBorba09** [comment]
I think JSON.stringfy() is ok for now
