### ISSUE TITLE
M1: Implement a folder structure

### ISSUE THREAD

**Issue by sebastianpiq** [montevideo-tech/cmcd-validator#40]
Create a folder structure for the library

- Suggestion: 

  - src
    - inputValidator
      - index.js
    - parser
      - index.js
    - CMCDValidator
      - index.js
    - utils
      - constants.js
      - helpers.js
    - index.js

In this structure, each module has its own folder with an index.js file that exports the module's functionality. The utilities folder contains two files, constants.js for storing constant values and helpers.js for storing auxiliary functions that can be used across multiple modules.
  
The index.js at src level file imports the modules (inputValidator, parser and CMCDValidator)

- index.js file example using modules:

```
import { validateHeaders } from './inputValidator';
import { parseHeaders } from './parser';
import { validateCMCDData } from './CMCDValidator';

const headers = {
  // Your input headers object here
};

// Validate input headers
if (validateHeaders(headers)) {
  // Parse headers
  const parsedHeaders = parseHeaders(headers);

  // Validate CMCD data
  if (validateCMCDData(parsedHeaders)) {
    console.log('CMCD data is valid!');
  } else {
    console.log('CMCD data is invalid.');
  }
} else {
  console.log('Invalid headers input.');
}
```

**Comment by sebastianpiq** [comment]
@CamiloBorba09 @mcamardon @arrivillagaTomas what do you think about this?

**Comment by mpollingerQualabs** [comment]
Looks good to me

**Comment by CamiloBorba09** [comment]
I cheked and it sounds good to me.
