### ISSUE TITLE
M1: Add lerna

### ISSUE THREAD

**Issue by Unnil** [montevideo-tech/cmcd-validator#41]

**Comment by sebastianpiq** [comment]
As I understand Lerna is for managing multiple packages in the same repo. Is this necessary for the M1 or is taking into account the management of the library + express-proxy-server + react error monitoring app in the future?

**Comment by nicolaslevy** [comment]
You are right for M1 is not necessary, but I see this reasons to do it anyway: 

1. The structure of the repo will change a lot, so it's better to do it before more people joins this challenge
2. People will be able to contribute with packages here with samples of players or other kind of use cases.
3. If you do a CI/CD pipeline, you will have to re-work on it after the repo changes (so don't do it twice as the effort to add lenra is very very low)
