### ISSUE TITLE
M1.5: Delete console logs and add  description to the function createError

### ISSUE THREAD

**Issue by CamiloBorba09** [montevideo-tech/cmcd-validator#58]
In the file `cmcd-validator/packages/cmcd-validator-library/src/keyValueValidator/validatorFunctions.js` we have severals console.log that are really usefull to debug. The idea of this ticket is to add this messages to the description of the error function. For example, we have: 

```
export const checkMaxLength = (errors, key, value) => {
  if (value.length > 64) {
    console.log(`Invalid value for key '${key}'. Maximum length is 64 characters.`);
    errors.push(createError(errorTypes.invalidValue, key, value));
  }
};
```
and the idea is to change to something like that

```
export const checkMaxLength = (errors, key, value) => {
  if (value.length > 64) {
    const description = `Invalid value for key '${key}'. Maximum length is 64 characters.`;
    errors.push(createError(errorTypes.invalidValue, key, value, description));
  }
};
```

AC:
1. Delete the console.logs and add the description to the createError function

**Comment by rodrigo-mira** [comment]
Also, same kind of changes has been applied to formatfunctions.js file
