### ISSUE TITLE
M2 Add HLS.js player to demo app

### ISSUE THREAD

**Issue by arrivillagaTomas** [montevideo-tech/cmcd-validator#83]
Add a HLS.js video player to the example demo app.
Implementation can be either stacked below the Shaka player one, or a selector can be created that toggles through the HLS or the Shaka player.

**AC**
1. HLS.js video player gets added to the demo app
2. HLS.js video player has the same functionality as the shaka player.

**Comment by CamiloBorba09** [comment]
This ticket is blocked by https://github.com/montevideo-tech/cmcd-validator/issues/130
