### ISSUE TITLE
M1: Publish the first functional version of the library on NPM

### ISSUE THREAD

**Issue by mpollingerQualabs** [montevideo-tech/cmcd-validator#9]
Publish the first functional version (v0.1) of the library on NPM using the name `cmcd-validator`

**Acceptance Criteria**:
- The library is available on NPM
- The library has documentation in npmjs that covers a simple example

**Comment by Rspillere** [comment]
The NPM organization for Montevideo-Tech has already been created as [montevideo-tech](https://www.npmjs.com/org/montevideo-tech)

We'll be using Lerna to create a multipackage monorepo, so there are a few things to keep in mind:

* Packages that won't be published on npm must have the private property enabled in their package.json file.
* The Lerna command for publishing is:
```
npx lerna publish --no-private
```
* To manage package versions, use the command:
```
lerna version --no-private
```
This will open a Lerna CLI that will guide you through the versioning process.

For more information on using Lerna, please visit the official [Lerna website](https://lerna.js.org/docs/features/version-and-publish) website
